# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'linkmap_ios/version'

Gem::Specification.new do |spec|
  spec.name          = "linkmap_ios"
  spec.version       = LinkmapIos::VERSION
  spec.authors       = ["Jesse Luo"]
  spec.email         = ["radishchrist@gmail.com"]

  spec.summary       = %q{A ruby library to parse linkmap file generated by Xcode}
  spec.description   = %q{A ruby library to parse linkmap file generated by Xcode.
                          Then ouput result with hash, json or report.
                          Also have a command line tool
                        }
  spec.homepage      = "https://github.com/jesseluo/linkmap_ios"
  spec.license       = "MIT"

  # Prevent pushing this gem to RubyGems.org. To allow pushes either set the 'allowed_push_host'
  # to allow pushing to a single host or delete this section to allow pushing to any host.
  # if spec.respond_to?(:metadata)
  #   spec.metadata['allowed_push_host'] = "TODO: Set to 'http://mygemserver.com'"
  # else
  #   raise "RubyGems 2.0 or newer is required to protect against public gem pushes."
  # end

  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  spec.bindir        = "bin"
  spec.executables   = ["linkmap_ios"]
  spec.require_paths = ["lib"]

  spec.add_dependency "thor", "~> 0.19.1"
  spec.add_dependency "filesize", "~> 0.1.1"

  spec.add_development_dependency "bundler", "~> 1.12"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec", "~> 3.0"
end
